/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2f42cff8-deef-466e-9b4d-64ebaea415ae",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tTWJdjZx8",
    "aws_user_pools_web_client_id": "67c1h6fbp3lhfd24tl66tcvnhe",
    "oauth": {},
    "aws_user_files_s3_bucket": "vcbucketdev125850-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2nacaduj6re33fztveuectnunq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-jfwjfrbl5zfafiivq4hkranqdu"
};


export default awsmobile;
