/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2f42cff8-deef-466e-9b4d-64ebaea415ae",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tTWJdjZx8",
    "aws_user_pools_web_client_id": "67c1h6fbp3lhfd24tl66tcvnhe",
    "oauth": {}
};


export default awsmobile;
